# Site settings
title: Wellspring Fellowship Songs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: /song/:title
# Build settings
markdown: kramdown
